// Generated by CoffeeScript 1.7.1
(function(_arg) {
  var sprites;
  sprites = _arg.sprites;
  return {
    title: "Rock-N-Roll Turtles",
    subtitle: "Page 1",
    contents: {
      controls: ['North', ['West', 'East'], 'South'],
      roster: sprites.map(function(sprite) {
        var color, facing, isCurrent, title, x, y;
        return {
          destroy_button: "X",
          sprite: (title = sprite.title, x = sprite.x, y = sprite.y, facing = sprite.facing, color = sprite.color, isCurrent = sprite.isCurrent, sprite)
        };
      })
    }
  };
});
